const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
class Element{
 constructor(id=''){this.id=id;this.value='';this.hidden=false;this.checked=true;this.disabled=false;this.readyState=4;this.videoWidth=1200;this.videoHeight=1600;this.children=[];this.listeners={};this.style={setProperty(k,v){this[k]=v;}};this.classes=new Set();this.classList={toggle:(k,v)=>{if(v===undefined)v=!this.classes.has(k);v?this.classes.add(k):this.classes.delete(k);return v;},add:(...xs)=>xs.forEach(k=>this.classes.add(k)),remove:(...xs)=>xs.forEach(k=>this.classes.delete(k))};this.dataset={};}
 addEventListener(n,f){(this.listeners[n]??=[]).push(f);} removeEventListener(n,f){this.listeners[n]=(this.listeners[n]||[]).filter(x=>x!==f);} async trigger(n){for(const f of this.listeners[n]||[])await f({target:this,preventDefault(){}});}
 querySelectorAll(s){return this.children.flatMap(c=>c.children||[]).filter(c=>c.type==='checkbox'&&c.checked);}
 append(...x){this.children.push(...x);}replaceChildren(...x){this.children=x;}setAttribute(k,v){this[k]=v;}removeAttribute(k){delete this[k];}remove(){}focus(){}scrollIntoView(){}click(){}add(x){this.children.push(x);}showModal(){this.open=true;}close(){this.open=false;}animate(){}play(){return Promise.resolve();}
 getContext(){return {drawImage(){}};}toBlob(f){f(new Blob([new Uint8Array([255,216,255,224])],{type:'image/jpeg'}));}
}
const nodes=new Map(),html=fs.readFileSync('public/index.html','utf8');for(const [,id]of html.matchAll(/id="([^"]+)"/g)){assert(!nodes.has(id),'duplicate HTML ID '+id);nodes.set(id,new Element(id));}
for(const [id,v]of Object.entries({guideScale:'70',shoulderWidth:'100',opacity:'40',timer:'0',patientCode:'HS-TEST',compareZoom:'1'}))nodes.get(id).value=v;
const main=new Element(),body=new Element(),layoutButtons=['slider','two','hero','grid'].map(layout=>{const b=new Element();b.dataset.layout=layout;return b;});
const events={},revoked=new Set();let nextUrl=0;
const track={getSettings:()=>({width:1200,height:1600,facingMode:'environment'}),label:'Camera',stop(){},addEventListener(){}};
const c={console,crypto:require('node:crypto').webcrypto,Blob,TextEncoder,TextDecoder,AbortController,setTimeout:(f,t)=>t===1000?setTimeout(f,0):0,clearTimeout,setInterval(){},URL:{createObjectURL:()=>`blob:${++nextUrl}`,revokeObjectURL:u=>revoked.add(u)},Option:class{constructor(text,value){this.text=text;this.value=value;}},Image:class{set src(v){this.naturalWidth=1200;this.naturalHeight=1600;queueMicrotask(()=>this.onload?.());}decode(){return Promise.resolve();}},screen:{orientation:{angle:0}},navigator:{mediaDevices:{getUserMedia:async()=>({getTracks:()=>[track],getVideoTracks:()=>[track]}),enumerateDevices:async()=>[]}},document:{hidden:false,getElementById:id=>{assert(nodes.has(id),'missing id '+id);return nodes.get(id);},createElement:()=>new Element(),querySelector:s=>s==='main'?main:null,querySelectorAll:s=>s==='[data-layout]'?layoutButtons:[],body,addEventListener(n,f){events[n]=f;}},window:{confirm:()=>true,addEventListener(n,f){(events[n]??=[]).push(f);}}};

(async()=>{
const {api}=await import('../server/api.mjs'),{DatabaseSync}=require('node:sqlite');
const sqlite=new DatabaseSync(':memory:');sqlite.exec(fs.readFileSync('migrations/0001_patients.sql','utf8'));
const objects=new Map(),env={DB:{prepare(sql){return {bind(...args){const s=sqlite.prepare(sql);return {first:async()=>s.get(...args),all:async()=>({results:s.all(...args)}),run:async()=>({meta:s.run(...args)})};}}}},BUCKET:{put:async(k,v)=>objects.set(k,v),get:async k=>objects.has(k)?{body:objects.get(k)}:null}};
let offline=false;
c.fetch=async(path,options={})=>{if(offline)throw Error('Offline');return api(new Request('https://test.example'+path,{...options,headers:{...options.headers,'Origin':'https://test.example'}}),env,{studioId:'studio-a'});};
vm.createContext(c);vm.runInContext(['app.js','workflow.js','cloud.js','presentation.js','device.js'].map(f=>fs.readFileSync('public/'+f,'utf8')).join('\n')+`\nglobalThis.t={cloud,cloudJSON,openCloudPatient,syncCloud,safePatientChange,cloudDirty,refreshPatients,capture,startCamera,selectPose,setView,render,rememberVisit,buildPhotoPDF,pairedPoses,sequenceIds,resetSession,state:()=>({visits,activeVisit,photos,view,pending,current,comparePose}),setCompare:(a,b,p)=>{compareA=a;compareB=b;comparePose=p;renderComparison();},makeBefore:(id,p)=>{visits[0].photos.set(id,p);render();}}`,c);
const t=c.t;await t.refreshPatients();assert(nodes.get('patientDialog').open);
const id=crypto.randomUUID(),otherId=crypto.randomUUID();await t.cloudJSON('/'+id,{code:'HS-A',name:'Alice Test'});await t.openCloudPatient(id);assert.equal(t.cloud.patient.code,'HS-A');await t.syncCloud();assert.equal(t.cloudDirty(),false);
// Patient notes save without photos and remain independent of visit treatment.
nodes.get('patientNotes').value='Allergie riferite: nessuna\nControllo fra 30 giorni <test>';
await nodes.get('patientNotes').trigger('input');assert(t.cloudDirty());await t.syncCloud();await t.openCloudPatient(id);
assert.equal(nodes.get('patientNotes').value,'Allergie riferite: nessuna\nControllo fra 30 giorni <test>');
await t.startCamera();await t.capture();await nodes.get('accept').trigger('click');assert.equal(t.cloudDirty(),true);assert.match(nodes.get('cloudStatus').textContent,/Da salvare/);assert(await t.syncCloud());assert.equal(t.cloudDirty(),false);assert.equal(nodes.get('cloudStatus').textContent,'Salvato nel cloud');
const photo=t.state().photos.get('front-neutral');photo.alignment={version:1,angle:0,points:[[.4,.4],[.6,.4]]};photo.brightness=12;t.makeBefore('profile-right',{...photo});await t.syncCloud();
nodes.get('treatment').value='Prima';await nodes.get('treatment').trigger('input');await t.syncCloud();await t.openCloudPatient(id);assert.equal(t.state().photos.size,2);assert.equal(t.state().photos.get('front-neutral').brightness,12);assert.equal(t.state().photos.get('front-neutral').alignment.version,1);assert.equal(nodes.get('treatment').value,'Prima');
await nodes.get('repeatPhotos').trigger('click');const checks=nodes.get('repeatChoices').querySelectorAll('input:checked');checks[0].checked=false;nodes.get('repeatPhase').value='followup';nodes.get('repeatTreatment').value='Trattamento test';await nodes.get('beginRepeat').trigger('click');assert.equal(t.state().activeVisit,1);assert.equal(t.state().current,3);assert.deepEqual(Array.from(t.sequenceIds()),['profile-right']);assert.equal(nodes.get('referenceImage').src,t.state().visits[0].photos.get('profile-right').url);
await t.startCamera();await t.capture();await nodes.get('accept').trigger('click');assert.equal(t.state().photos.size,1);assert.equal(t.state().current,3);assert.equal(nodes.get('progressText').textContent,'1 / 1');await t.syncCloud();await t.openCloudPatient(id);assert.equal(t.state().visits[1].photos.size,1);assert.equal(t.state().visits[1].treatment,'Trattamento test');assert.deepEqual(Array.from(t.state().visits[1].selected),['profile-right']);
t.setView('compare');t.setCompare(0,1,'profile-right');await nodes.get('patientMode').trigger('click');assert(body.classes.has('patient-mode'));assert.equal(nodes.get('patientNavigation').hidden,false);await nodes.get('exitPatientMode').trigger('click');assert(!body.classes.has('patient-mode'));
// Failed save cannot say saved or switch to another patient.
t.setView('before');offline=true;nodes.get('treatment').value='Offline draft';await nodes.get('treatment').trigger('input');assert.equal(await t.syncCloud(),false);assert(t.cloudDirty());assert.match(nodes.get('cloudStatus').textContent,/Da salvare/);assert.equal(await t.safePatientChange(),false);
offline=false;await nodes.get('retryCloud').trigger('click');await t.syncCloud();assert.equal(t.cloudDirty(),false);
// A stale client must preserve its local work and reject overwrites.
t.cloud.version--;nodes.get('treatment').value='Stale draft';await nodes.get('treatment').trigger('input');assert.equal(await t.syncCloud(),false);assert(t.cloud.conflict);assert(t.cloudDirty());await t.openCloudPatient(id,{force:true});assert.equal(nodes.get('treatment').value,'Offline draft');
await t.cloudJSON('/'+otherId,{code:'HS-B',name:'Bob Test'});await t.openCloudPatient(otherId);assert.equal(t.state().photos.size,0);assert.equal(t.state().visits.length,1);assert.equal(nodes.get('patientCode').value,'HS-B');assert.equal(nodes.get('patientNotes').value,'');await t.syncCloud();await t.openCloudPatient(id);assert.equal(t.state().visits.length,2);assert.equal(t.state().visits[0].photos.size,2);
assert.match(nodes.get('patientNotes').value,/Controllo fra 30 giorni/);
nodes.get('patientNotes').value='';await nodes.get('patientNotes').trigger('input');await t.syncCloud();await t.openCloudPatient(id);assert.equal(nodes.get('patientNotes').value,'');
const pdf=t.buildPhotoPDF([{bytes:new Uint8Array([255,216,255,217]),width:1,height:1}]);const data=Buffer.from(await pdf.arrayBuffer());assert(data.toString().startsWith('%PDF-1.4'));const xref=Number(data.toString().match(/startxref\n(\d+)/)[1]);assert.equal(data.subarray(xref,xref+4).toString(),'xref');
console.log('PASS: full client/API cloud save and reload, patient isolation, saved status, offline retry, blocked switch, conflict recovery, selective retake/ghost, patient mode, PDF offsets.');
})().catch(e=>{console.error(e);process.exitCode=1;});
