export const PAGE=String.raw`<!doctype html><html lang="it"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Lettore agenda Healthy Smile</title>
<style>body{font:16px system-ui;max-width:1100px;margin:30px auto;padding:0 20px;color:#20252b;background:#f5f7fa}fieldset,article{background:white;border:1px solid #ccc;border-radius:8px;padding:18px;margin:16px 0}button{padding:12px;margin:8px 8px 8px 0;cursor:pointer}label{display:block;margin:10px 0}select,input{padding:8px;max-width:100%}table{border-collapse:collapse;width:100%}td,th{padding:8px;border-bottom:1px solid #ddd;text-align:left}pre{white-space:pre-wrap;overflow-wrap:anywhere}#message{font-weight:bold;white-space:pre-wrap}.warn{color:#9a3412}summary{cursor:pointer;padding:8px}.scroll{overflow:auto}</style>
<h1>Lettore agenda</h1><p>Legge Teamup e spiega ogni giornata. Non modifica eventi, prenotazioni o pagamenti e non pubblica slot sul sito.</p>
<p>Interpretazione con regole esplicite: gli avvisi sconosciuti vengono segnalati. Non è ancora un interprete AI del testo libero.</p>
<label>Token amministratore <input id="token" type="password" autocomplete="off"></label><button id="connect">Connetti</button><p id="message" role="status"></p>
<fieldset id="config" hidden><legend>Agende</legend><p>Spunta solo i calendari Medici. Identifica anche l’agenda dell’igienista.</p><div id="choices"></div>
<label>Dott. Palmia: apertura e pause <select id="palmia"></select></label><label>Prenotazioni sito (facoltativo) <select id="site"></select></label>
<label><input id="staff" type="checkbox"> Confermo che l’igienista segue l’apertura di Palmia</label><button id="save">Salva configurazione lettore</button></fieldset>
<section id="actions" hidden><label>Giornata <input id="date" type="date"></label><button id="day">Leggi questa giornata adesso</button><button id="all">Leggi prossimi 14 giorni</button><button id="reload">Mostra ultima lettura</button><p id="last"></p></section><div id="reports"></div>
<script>
const $=id=>document.getElementById(id);let token='',busy=false;
async function api(path,body){const r=await fetch('/api/'+path,{method:body?'POST':'GET',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined,cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d.error||'Errore '+r.status);return d;}
async function run(fn){if(busy)return;busy=true;$('message').textContent='Lettura in corso…';try{await fn();}catch(e){$('message').textContent=e.message;}finally{busy=false;}}
function text(tag,value,parent){const e=document.createElement(tag);e.textContent=value;parent.append(e);return e;}
function render(d){$('reports').replaceChildren();if(!d.reports.length)text('p','Nessuna lettura salvata. Premi Leggi questa giornata adesso.',$('reports'));
for(const r of d.reports){const a=document.createElement('article');$('reports').append(a);text('h2',r.date+' — '+r.candidate_count+' inizi candidati',a);text('p','Letta: '+new Date(r.checked_at).toLocaleString('it-IT')+(r.stale?' — DATI DA AGGIORNARE':''),a);
if(r.error){text('p',r.error,a).className='warn';continue;}
text('p','Fasce interpretate: '+(r.windows.map(w=>new Date(w.start_dt).toLocaleTimeString('it-IT',{timeZone:'Europe/Rome',hour:'2-digit',minute:'2-digit'})+'–'+new Date(w.end_dt).toLocaleTimeString('it-IT',{timeZone:'Europe/Rome',hour:'2-digit',minute:'2-digit'})).join(', ')||'nessuna'),a);
for(const i of r.issues)text('p',(i.event_id?'Evento '+i.event_id+': ':'')+i.reason,a).className='warn';text('p',r.note,a);
text('p','Candidati: '+(r.slots.filter(s=>s.status==='candidate').map(s=>s.time).join(', ')||'nessuno'),a);
const details=document.createElement('details');a.append(details);text('summary','Cosa ho letto e come l’ho interpretato ('+r.events.length+' eventi)',details);
for(const e of r.events)text('pre',e.event_id+' | '+e.title+'\n'+e.start_dt+' → '+e.end_dt+'\nCalendari: '+e.calendar_ids.join(', ')+'\n'+e.reason+(e.notes?'\nNote: '+e.notes:''),details);
const slots=document.createElement('details');a.append(slots);text('summary','Motivo per ciascun orario, anche quelli esclusi',slots);const table=document.createElement('table');slots.append(table);
for(const s of r.slots){const tr=document.createElement('tr');table.append(tr);text('td',s.time,tr);text('td',s.chairs_peak+' poltrone occupate (massimo)',tr);text('td',s.reasons.join('; ')||'Capienza e igienista compatibili',tr);}}
if(d.run)$('last').textContent='Ultimo ciclo: '+(d.run.finished_at||d.run.attempted_at||'—')+(d.run.error?' — '+d.run.error:'');}
$('connect').onclick=()=>run(async()=>{token=$('token').value;const d=await api('config');$('choices').replaceChildren();$('palmia').replaceChildren(new Option('Seleziona',''));$('site').replaceChildren(new Option('Nessuno',''));for(const c of d.calendars){const row=document.createElement('div');$('choices').append(row);const label=document.createElement('label'),check=document.createElement('input');check.type='checkbox';check.dataset.medical=c.id;check.checked=!!d.config?.medical_ids.includes(c.id);label.append(check,document.createTextNode(c.name+' ['+c.id+']'));row.append(label);const hl=document.createElement('label'),hc=document.createElement('input');hc.type='checkbox';hc.dataset.hygiene=c.id;hc.checked=!!d.config?.hygienist_ids.includes(c.id);hl.append(hc,document.createTextNode('Agenda igienista'));row.append(hl);$('palmia').add(new Option(c.name,c.id));$('site').add(new Option(c.name,c.id));}
$('palmia').value=d.config?.palmia_id||'';$('site').value=d.config?.site_id||'';$('staff').checked=!!d.config?.staff_follows_palmia;$('config').hidden=false;$('actions').hidden=false;$('date').value=new Date().toLocaleDateString('sv-SE',{timeZone:'Europe/Rome'});$('message').textContent='Connesso. Configura le agende e avvia una lettura.';});
$('save').onclick=()=>run(async()=>{await api('config',{medical_ids:[...document.querySelectorAll('[data-medical]:checked')].map(x=>+x.dataset.medical),hygienist_ids:[...document.querySelectorAll('[data-hygiene]:checked')].map(x=>+x.dataset.hygiene),palmia_id:+$('palmia').value,site_id:+$('site').value||null,staff_follows_palmia:$('staff').checked});$('message').textContent='Configurazione del lettore salvata. Nessuna modifica al sito.';});
$('day').onclick=()=>run(async()=>{if(!$('date').value)throw Error('Scegli la giornata');render(await api('scan',{date:$('date').value}));$('message').textContent='Lettura completata. Controlla interpretazione e motivi qui sotto.';});
$('all').onclick=()=>run(async()=>{render(await api('scan',{}));$('message').textContent='Lettura completata.';});
$('reload').onclick=()=>run(async()=>{render(await api('reports'));$('message').textContent='Risultati caricati.';});
</script></html>`;
