import {readFile,writeFile} from 'node:fs/promises';
const root=new URL('./',import.meta.url);
const core=await readFile(new URL('clinical-core.js',root),'utf8');
const worker=await readFile(new URL('worker-entry.js',root),'utf8');
await writeFile(new URL('odontogramma-v6.mjs',root),'// Generated by node ai/build-worker.mjs — standalone Cloudflare module.\n'+core+'\n'+worker);
