import {test} from 'node:test';import assert from 'node:assert/strict';
import worker,{outputSchema,buildPrompt} from '../odontogramma-v6.mjs';
const ctx={studio_id:'test',doctor_id:'doctor',listino_attuale:[{id:'cariato',label:'Cariato'}],listino_piano:[{id:'restauro',label:'Restauro composito',scope:'TOOTH_LEVEL',prezzo:100}],patient_context:{},correction_memory:[]};
const proposal={transcription_corrected:'carie distale 12',findings:[{target:'12',description:'Carie distale',id_listino:'cariato',note:'',evidence:'carie distale 12',confidence:0.9}],treatments:[{target:'12',label:'Restauro composito',id_listino:'restauro',scope:'TOOTH_LEVEL',status:'dafare',qta:1,diagnosis:'Carie distale',rationale:'Proposta da confermare',note:'',evidence:'carie distale 12',needs_review:false,confidence:0.8}],suggestions:[],summary:'Proposta da verificare',issues:[],warnings:[]};
const request=()=>new Request('https://worker.test',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...ctx,trascrizione:'carie distale 12'})});
test('schema uses real catalogue IDs and forbids unknown object properties',()=>{const s=outputSchema(ctx);assert.equal(s.additionalProperties,false);assert.deepEqual(s.properties.treatments.items.properties.id_listino.enum,['','restauro']);assert.ok(s.properties.treatments.items.required.includes('label'));});
test('reasoning prompt preserves healthy convention and does not coerce every problem into caries',()=>{const p=buildPrompt(ctx,'carie');assert.match(p,/NON menzionati/);assert.match(p,/Non trasformare tutti i problemi/);assert.match(p,/Non inventare una diagnosi a partire/);});
test('end-to-end mocked request keeps label+stato compatibility and QC cannot overwrite treatments',async()=>{
 const original=globalThis.fetch,calls=[];globalThis.fetch=async(url,opt)=>{const payload=JSON.parse(opt.body);calls.push(payload);return Response.json({choices:[{finish_reason:'stop',message:{content:JSON.stringify(calls.length===1?proposal:{issues:['Verificare profondità'],warnings:[]})}}]});};
 try{const r=await worker.fetch(request(),{OPENAI_API_KEY:'test'});assert.equal(r.status,200);const d=await r.json();assert.equal(d.treatments[0].id_listino,'restauro');assert.equal(d.terapie_da_attuare.denti[12].terapie[0].stato,'Restauro composito');assert.ok(d.issues.includes('Verificare profondità'));assert.equal(d._meta.contract_version,6);assert.equal(calls[0].response_format.json_schema.strict,true);assert.match(calls[1].messages[1].content,/carie distale 12/);assert.match(calls[1].messages[1].content,/listino_piano/);}
 finally{globalThis.fetch=original;}
});
test('truncated API responses fail instead of reporting ready',async()=>{const old=globalThis.fetch;globalThis.fetch=async()=>Response.json({choices:[{finish_reason:'length',message:{content:'{}'}}]});try{const r=await worker.fetch(request(),{OPENAI_API_KEY:'test'});assert.equal(r.status,502);assert.match((await r.json()).error,/incompleta/);}finally{globalThis.fetch=old;}});
test('QC outage retains draft and adds visible warning',async()=>{const old=globalThis.fetch;let n=0;globalThis.fetch=async()=>++n===1?Response.json({choices:[{finish_reason:'stop',message:{content:JSON.stringify(proposal)}}]}):new Response('',{status:500});try{const d=await (await worker.fetch(request(),{OPENAI_API_KEY:'test'})).json();assert.equal(d.treatments.length,1);assert.ok(d.warnings.some(w=>w.includes('Controllo aggiuntivo')));}finally{globalThis.fetch=old;}});
test('audio note accumulates previous dictation before analysis',async()=>{const old=globalThis.fetch;let modelInput='';globalThis.fetch=async(url,opt)=>{if(url.endsWith('/transcriptions'))return Response.json({text:'e distale 13'});const b=JSON.parse(opt.body);if(b.model==='gpt-4.1')modelInput=b.messages[1].content;return Response.json({choices:[{finish_reason:'stop',message:{content:JSON.stringify(b.model==='gpt-4.1'?proposal:{issues:[],warnings:[]})}}]});};try{const form=new FormData();form.append('audio',new Blob(['synthetic'],{type:'audio/webm'}),'recording.webm');form.append('note_prefix','carie 12');form.append('listino_attuale',JSON.stringify(ctx.listino_attuale));form.append('listino_piano',JSON.stringify(ctx.listino_piano));const r=await worker.fetch(new Request('https://worker.test',{method:'POST',body:form}),{OPENAI_API_KEY:'test'});assert.equal(r.status,200);assert.match(modelInput,/carie 12\ne distale 13/);}finally{globalThis.fetch=old;}});
